import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
REPO = ROOT.parents[0]
sys.path.insert(0, str(ROOT))
from latticeguard.github_sync import build_sync_manifest
entries = build_sync_manifest(REPO)
assert entries, 'sync manifest cannot be empty'
paths = {e.path for e in entries}
assert 'artifact/scripts/verify_all.py' in paths
assert 'paper/main.tex' in paths
large = [e for e in entries if e.upload_mode == 'manifest_only']
assert any(e.path.endswith('model_check_cases.csv') for e in large), 'large deterministic model-check case table should be manifest-only'
assert not any('__pycache__' in e.path and e.upload_mode != 'exclude' for e in entries)
assert not any('subjects/fixtures/' in e.path for e in entries), 'generated fixtures are regenerated by replay and must not bloat sync manifest'
print('github_sync_manifest PASS')
