from __future__ import annotations
from dataclasses import dataclass
@dataclass(frozen=True)
class ReviewCheck:
    check_id: str
    category: str
    question: str
    evidence_file: str
    expected: str
    severity: str
    repair: str
REVIEW_PLAYBOOK = [
    ReviewCheck(
        check_id='REPRODUCIBILITY_001',
        category='reproducibility',
        question='Does the repository provide auditable reproducibility evidence for REPRODUCIBILITY_001?',
        evidence_file='evidence/SHA256SUMS.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for reproducibility.',
    ),
    ReviewCheck(
        check_id='BENCHMARK_002',
        category='benchmark',
        question='Does the repository provide auditable benchmark evidence for BENCHMARK_002?',
        evidence_file='source_manifest.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for benchmark.',
    ),
    ReviewCheck(
        check_id='PREDICATE_003',
        category='predicate',
        question='Does the repository provide auditable predicate evidence for PREDICATE_003?',
        evidence_file='results/predicate_evaluations.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for predicate.',
    ),
    ReviewCheck(
        check_id='THEORY_004',
        category='theory',
        question='Does the repository provide auditable theory evidence for THEORY_004?',
        evidence_file='results/model_check_summary.json',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for theory.',
    ),
    ReviewCheck(
        check_id='ADAPTER_005',
        category='adapter',
        question='Does the repository provide auditable adapter evidence for ADAPTER_005?',
        evidence_file='results/adapter_semantics_matrix.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for adapter.',
    ),
    ReviewCheck(
        check_id='COUNTEREXAMPLE_006',
        category='counterexample',
        question='Does the repository provide auditable counterexample evidence for COUNTEREXAMPLE_006?',
        evidence_file='results/counterexamples.json',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for counterexample.',
    ),
    ReviewCheck(
        check_id='MANIFEST_007',
        category='manifest',
        question='Does the repository provide auditable manifest evidence for MANIFEST_007?',
        evidence_file='source_manifest.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for manifest.',
    ),
    ReviewCheck(
        check_id='HYGIENE_008',
        category='hygiene',
        question='Does the repository provide auditable hygiene evidence for HYGIENE_008?',
        evidence_file='scripts/verify_anonymity_and_hygiene.py',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for hygiene.',
    ),
    ReviewCheck(
        check_id='BASELINE_009',
        category='baseline',
        question='Does the repository provide auditable baseline evidence for BASELINE_009?',
        evidence_file='results/baseline_results.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for baseline.',
    ),
    ReviewCheck(
        check_id='COVERAGE_010',
        category='coverage',
        question='Does the repository provide auditable coverage evidence for COVERAGE_010?',
        evidence_file='results/coverage_lattice.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for coverage.',
    ),
    ReviewCheck(
        check_id='REPRODUCIBILITY_011',
        category='reproducibility',
        question='Does the repository provide auditable reproducibility evidence for REPRODUCIBILITY_011?',
        evidence_file='evidence/SHA256SUMS.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for reproducibility.',
    ),
    ReviewCheck(
        check_id='BENCHMARK_012',
        category='benchmark',
        question='Does the repository provide auditable benchmark evidence for BENCHMARK_012?',
        evidence_file='source_manifest.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for benchmark.',
    ),
    ReviewCheck(
        check_id='PREDICATE_013',
        category='predicate',
        question='Does the repository provide auditable predicate evidence for PREDICATE_013?',
        evidence_file='results/predicate_evaluations.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for predicate.',
    ),
    ReviewCheck(
        check_id='THEORY_014',
        category='theory',
        question='Does the repository provide auditable theory evidence for THEORY_014?',
        evidence_file='results/model_check_summary.json',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for theory.',
    ),
    ReviewCheck(
        check_id='ADAPTER_015',
        category='adapter',
        question='Does the repository provide auditable adapter evidence for ADAPTER_015?',
        evidence_file='results/adapter_semantics_matrix.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for adapter.',
    ),
    ReviewCheck(
        check_id='COUNTEREXAMPLE_016',
        category='counterexample',
        question='Does the repository provide auditable counterexample evidence for COUNTEREXAMPLE_016?',
        evidence_file='results/counterexamples.json',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for counterexample.',
    ),
    ReviewCheck(
        check_id='MANIFEST_017',
        category='manifest',
        question='Does the repository provide auditable manifest evidence for MANIFEST_017?',
        evidence_file='source_manifest.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for manifest.',
    ),
    ReviewCheck(
        check_id='HYGIENE_018',
        category='hygiene',
        question='Does the repository provide auditable hygiene evidence for HYGIENE_018?',
        evidence_file='scripts/verify_anonymity_and_hygiene.py',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for hygiene.',
    ),
    ReviewCheck(
        check_id='BASELINE_019',
        category='baseline',
        question='Does the repository provide auditable baseline evidence for BASELINE_019?',
        evidence_file='results/baseline_results.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for baseline.',
    ),
    ReviewCheck(
        check_id='COVERAGE_020',
        category='coverage',
        question='Does the repository provide auditable coverage evidence for COVERAGE_020?',
        evidence_file='results/coverage_lattice.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for coverage.',
    ),
    ReviewCheck(
        check_id='REPRODUCIBILITY_021',
        category='reproducibility',
        question='Does the repository provide auditable reproducibility evidence for REPRODUCIBILITY_021?',
        evidence_file='evidence/SHA256SUMS.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for reproducibility.',
    ),
    ReviewCheck(
        check_id='BENCHMARK_022',
        category='benchmark',
        question='Does the repository provide auditable benchmark evidence for BENCHMARK_022?',
        evidence_file='source_manifest.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for benchmark.',
    ),
    ReviewCheck(
        check_id='PREDICATE_023',
        category='predicate',
        question='Does the repository provide auditable predicate evidence for PREDICATE_023?',
        evidence_file='results/predicate_evaluations.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for predicate.',
    ),
    ReviewCheck(
        check_id='THEORY_024',
        category='theory',
        question='Does the repository provide auditable theory evidence for THEORY_024?',
        evidence_file='results/model_check_summary.json',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for theory.',
    ),
    ReviewCheck(
        check_id='ADAPTER_025',
        category='adapter',
        question='Does the repository provide auditable adapter evidence for ADAPTER_025?',
        evidence_file='results/adapter_semantics_matrix.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for adapter.',
    ),
    ReviewCheck(
        check_id='COUNTEREXAMPLE_026',
        category='counterexample',
        question='Does the repository provide auditable counterexample evidence for COUNTEREXAMPLE_026?',
        evidence_file='results/counterexamples.json',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for counterexample.',
    ),
    ReviewCheck(
        check_id='MANIFEST_027',
        category='manifest',
        question='Does the repository provide auditable manifest evidence for MANIFEST_027?',
        evidence_file='source_manifest.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for manifest.',
    ),
    ReviewCheck(
        check_id='HYGIENE_028',
        category='hygiene',
        question='Does the repository provide auditable hygiene evidence for HYGIENE_028?',
        evidence_file='scripts/verify_anonymity_and_hygiene.py',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for hygiene.',
    ),
    ReviewCheck(
        check_id='BASELINE_029',
        category='baseline',
        question='Does the repository provide auditable baseline evidence for BASELINE_029?',
        evidence_file='results/baseline_results.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for baseline.',
    ),
    ReviewCheck(
        check_id='COVERAGE_030',
        category='coverage',
        question='Does the repository provide auditable coverage evidence for COVERAGE_030?',
        evidence_file='results/coverage_lattice.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for coverage.',
    ),
    ReviewCheck(
        check_id='REPRODUCIBILITY_031',
        category='reproducibility',
        question='Does the repository provide auditable reproducibility evidence for REPRODUCIBILITY_031?',
        evidence_file='evidence/SHA256SUMS.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for reproducibility.',
    ),
    ReviewCheck(
        check_id='BENCHMARK_032',
        category='benchmark',
        question='Does the repository provide auditable benchmark evidence for BENCHMARK_032?',
        evidence_file='source_manifest.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for benchmark.',
    ),
    ReviewCheck(
        check_id='PREDICATE_033',
        category='predicate',
        question='Does the repository provide auditable predicate evidence for PREDICATE_033?',
        evidence_file='results/predicate_evaluations.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for predicate.',
    ),
    ReviewCheck(
        check_id='THEORY_034',
        category='theory',
        question='Does the repository provide auditable theory evidence for THEORY_034?',
        evidence_file='results/model_check_summary.json',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for theory.',
    ),
    ReviewCheck(
        check_id='ADAPTER_035',
        category='adapter',
        question='Does the repository provide auditable adapter evidence for ADAPTER_035?',
        evidence_file='results/adapter_semantics_matrix.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for adapter.',
    ),
    ReviewCheck(
        check_id='COUNTEREXAMPLE_036',
        category='counterexample',
        question='Does the repository provide auditable counterexample evidence for COUNTEREXAMPLE_036?',
        evidence_file='results/counterexamples.json',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for counterexample.',
    ),
    ReviewCheck(
        check_id='MANIFEST_037',
        category='manifest',
        question='Does the repository provide auditable manifest evidence for MANIFEST_037?',
        evidence_file='source_manifest.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for manifest.',
    ),
    ReviewCheck(
        check_id='HYGIENE_038',
        category='hygiene',
        question='Does the repository provide auditable hygiene evidence for HYGIENE_038?',
        evidence_file='scripts/verify_anonymity_and_hygiene.py',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for hygiene.',
    ),
    ReviewCheck(
        check_id='BASELINE_039',
        category='baseline',
        question='Does the repository provide auditable baseline evidence for BASELINE_039?',
        evidence_file='results/baseline_results.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for baseline.',
    ),
    ReviewCheck(
        check_id='COVERAGE_040',
        category='coverage',
        question='Does the repository provide auditable coverage evidence for COVERAGE_040?',
        evidence_file='results/coverage_lattice.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for coverage.',
    ),
    ReviewCheck(
        check_id='REPRODUCIBILITY_041',
        category='reproducibility',
        question='Does the repository provide auditable reproducibility evidence for REPRODUCIBILITY_041?',
        evidence_file='evidence/SHA256SUMS.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for reproducibility.',
    ),
    ReviewCheck(
        check_id='BENCHMARK_042',
        category='benchmark',
        question='Does the repository provide auditable benchmark evidence for BENCHMARK_042?',
        evidence_file='source_manifest.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for benchmark.',
    ),
    ReviewCheck(
        check_id='PREDICATE_043',
        category='predicate',
        question='Does the repository provide auditable predicate evidence for PREDICATE_043?',
        evidence_file='results/predicate_evaluations.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for predicate.',
    ),
    ReviewCheck(
        check_id='THEORY_044',
        category='theory',
        question='Does the repository provide auditable theory evidence for THEORY_044?',
        evidence_file='results/model_check_summary.json',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for theory.',
    ),
    ReviewCheck(
        check_id='ADAPTER_045',
        category='adapter',
        question='Does the repository provide auditable adapter evidence for ADAPTER_045?',
        evidence_file='results/adapter_semantics_matrix.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for adapter.',
    ),
    ReviewCheck(
        check_id='COUNTEREXAMPLE_046',
        category='counterexample',
        question='Does the repository provide auditable counterexample evidence for COUNTEREXAMPLE_046?',
        evidence_file='results/counterexamples.json',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for counterexample.',
    ),
    ReviewCheck(
        check_id='MANIFEST_047',
        category='manifest',
        question='Does the repository provide auditable manifest evidence for MANIFEST_047?',
        evidence_file='source_manifest.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for manifest.',
    ),
    ReviewCheck(
        check_id='HYGIENE_048',
        category='hygiene',
        question='Does the repository provide auditable hygiene evidence for HYGIENE_048?',
        evidence_file='scripts/verify_anonymity_and_hygiene.py',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for hygiene.',
    ),
    ReviewCheck(
        check_id='BASELINE_049',
        category='baseline',
        question='Does the repository provide auditable baseline evidence for BASELINE_049?',
        evidence_file='results/baseline_results.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for baseline.',
    ),
    ReviewCheck(
        check_id='COVERAGE_050',
        category='coverage',
        question='Does the repository provide auditable coverage evidence for COVERAGE_050?',
        evidence_file='results/coverage_lattice.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for coverage.',
    ),
    ReviewCheck(
        check_id='REPRODUCIBILITY_051',
        category='reproducibility',
        question='Does the repository provide auditable reproducibility evidence for REPRODUCIBILITY_051?',
        evidence_file='evidence/SHA256SUMS.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for reproducibility.',
    ),
    ReviewCheck(
        check_id='BENCHMARK_052',
        category='benchmark',
        question='Does the repository provide auditable benchmark evidence for BENCHMARK_052?',
        evidence_file='source_manifest.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for benchmark.',
    ),
    ReviewCheck(
        check_id='PREDICATE_053',
        category='predicate',
        question='Does the repository provide auditable predicate evidence for PREDICATE_053?',
        evidence_file='results/predicate_evaluations.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for predicate.',
    ),
    ReviewCheck(
        check_id='THEORY_054',
        category='theory',
        question='Does the repository provide auditable theory evidence for THEORY_054?',
        evidence_file='results/model_check_summary.json',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for theory.',
    ),
    ReviewCheck(
        check_id='ADAPTER_055',
        category='adapter',
        question='Does the repository provide auditable adapter evidence for ADAPTER_055?',
        evidence_file='results/adapter_semantics_matrix.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for adapter.',
    ),
    ReviewCheck(
        check_id='COUNTEREXAMPLE_056',
        category='counterexample',
        question='Does the repository provide auditable counterexample evidence for COUNTEREXAMPLE_056?',
        evidence_file='results/counterexamples.json',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for counterexample.',
    ),
    ReviewCheck(
        check_id='MANIFEST_057',
        category='manifest',
        question='Does the repository provide auditable manifest evidence for MANIFEST_057?',
        evidence_file='source_manifest.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for manifest.',
    ),
    ReviewCheck(
        check_id='HYGIENE_058',
        category='hygiene',
        question='Does the repository provide auditable hygiene evidence for HYGIENE_058?',
        evidence_file='scripts/verify_anonymity_and_hygiene.py',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for hygiene.',
    ),
    ReviewCheck(
        check_id='BASELINE_059',
        category='baseline',
        question='Does the repository provide auditable baseline evidence for BASELINE_059?',
        evidence_file='results/baseline_results.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for baseline.',
    ),
    ReviewCheck(
        check_id='COVERAGE_060',
        category='coverage',
        question='Does the repository provide auditable coverage evidence for COVERAGE_060?',
        evidence_file='results/coverage_lattice.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for coverage.',
    ),
    ReviewCheck(
        check_id='REPRODUCIBILITY_061',
        category='reproducibility',
        question='Does the repository provide auditable reproducibility evidence for REPRODUCIBILITY_061?',
        evidence_file='evidence/SHA256SUMS.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for reproducibility.',
    ),
    ReviewCheck(
        check_id='BENCHMARK_062',
        category='benchmark',
        question='Does the repository provide auditable benchmark evidence for BENCHMARK_062?',
        evidence_file='source_manifest.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for benchmark.',
    ),
    ReviewCheck(
        check_id='PREDICATE_063',
        category='predicate',
        question='Does the repository provide auditable predicate evidence for PREDICATE_063?',
        evidence_file='results/predicate_evaluations.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for predicate.',
    ),
    ReviewCheck(
        check_id='THEORY_064',
        category='theory',
        question='Does the repository provide auditable theory evidence for THEORY_064?',
        evidence_file='results/model_check_summary.json',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for theory.',
    ),
    ReviewCheck(
        check_id='ADAPTER_065',
        category='adapter',
        question='Does the repository provide auditable adapter evidence for ADAPTER_065?',
        evidence_file='results/adapter_semantics_matrix.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for adapter.',
    ),
    ReviewCheck(
        check_id='COUNTEREXAMPLE_066',
        category='counterexample',
        question='Does the repository provide auditable counterexample evidence for COUNTEREXAMPLE_066?',
        evidence_file='results/counterexamples.json',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for counterexample.',
    ),
    ReviewCheck(
        check_id='MANIFEST_067',
        category='manifest',
        question='Does the repository provide auditable manifest evidence for MANIFEST_067?',
        evidence_file='source_manifest.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for manifest.',
    ),
    ReviewCheck(
        check_id='HYGIENE_068',
        category='hygiene',
        question='Does the repository provide auditable hygiene evidence for HYGIENE_068?',
        evidence_file='scripts/verify_anonymity_and_hygiene.py',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for hygiene.',
    ),
    ReviewCheck(
        check_id='BASELINE_069',
        category='baseline',
        question='Does the repository provide auditable baseline evidence for BASELINE_069?',
        evidence_file='results/baseline_results.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for baseline.',
    ),
    ReviewCheck(
        check_id='COVERAGE_070',
        category='coverage',
        question='Does the repository provide auditable coverage evidence for COVERAGE_070?',
        evidence_file='results/coverage_lattice.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for coverage.',
    ),
    ReviewCheck(
        check_id='REPRODUCIBILITY_071',
        category='reproducibility',
        question='Does the repository provide auditable reproducibility evidence for REPRODUCIBILITY_071?',
        evidence_file='evidence/SHA256SUMS.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for reproducibility.',
    ),
    ReviewCheck(
        check_id='BENCHMARK_072',
        category='benchmark',
        question='Does the repository provide auditable benchmark evidence for BENCHMARK_072?',
        evidence_file='source_manifest.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for benchmark.',
    ),
    ReviewCheck(
        check_id='PREDICATE_073',
        category='predicate',
        question='Does the repository provide auditable predicate evidence for PREDICATE_073?',
        evidence_file='results/predicate_evaluations.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for predicate.',
    ),
    ReviewCheck(
        check_id='THEORY_074',
        category='theory',
        question='Does the repository provide auditable theory evidence for THEORY_074?',
        evidence_file='results/model_check_summary.json',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for theory.',
    ),
    ReviewCheck(
        check_id='ADAPTER_075',
        category='adapter',
        question='Does the repository provide auditable adapter evidence for ADAPTER_075?',
        evidence_file='results/adapter_semantics_matrix.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for adapter.',
    ),
    ReviewCheck(
        check_id='COUNTEREXAMPLE_076',
        category='counterexample',
        question='Does the repository provide auditable counterexample evidence for COUNTEREXAMPLE_076?',
        evidence_file='results/counterexamples.json',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for counterexample.',
    ),
    ReviewCheck(
        check_id='MANIFEST_077',
        category='manifest',
        question='Does the repository provide auditable manifest evidence for MANIFEST_077?',
        evidence_file='source_manifest.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for manifest.',
    ),
    ReviewCheck(
        check_id='HYGIENE_078',
        category='hygiene',
        question='Does the repository provide auditable hygiene evidence for HYGIENE_078?',
        evidence_file='scripts/verify_anonymity_and_hygiene.py',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for hygiene.',
    ),
    ReviewCheck(
        check_id='BASELINE_079',
        category='baseline',
        question='Does the repository provide auditable baseline evidence for BASELINE_079?',
        evidence_file='results/baseline_results.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for baseline.',
    ),
    ReviewCheck(
        check_id='COVERAGE_080',
        category='coverage',
        question='Does the repository provide auditable coverage evidence for COVERAGE_080?',
        evidence_file='results/coverage_lattice.csv',
        expected='present, deterministic, and verifier-backed',
        severity='P2',
        repair='Run the corresponding repository verifier and update the first-class ledger for coverage.',
    ),
]
def checks_by_category() -> dict[str, list[ReviewCheck]]:
    out: dict[str, list[ReviewCheck]] = {}
    for check in REVIEW_PLAYBOOK:
        out.setdefault(check.category, []).append(check)
    return out
def playbook_summary() -> dict[str, int]:
    return {category: len(items) for category, items in checks_by_category().items()}
def required_evidence_files() -> list[str]:
    return sorted({check.evidence_file for check in REVIEW_PLAYBOOK})
def missing_evidence(existing: set[str]) -> list[str]:
    return [path for path in required_evidence_files() if path not in existing]
