from __future__ import annotations
ATTACK_SURFACE = [
    {
        'attack_id': 'AS_001',
        'category': 'artifact',
        'audit_question': 'Can a strict assessor invalidate the artifact claim represented by AS_001?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_002',
        'category': 'benchmark',
        'audit_question': 'Can a strict assessor invalidate the benchmark claim represented by AS_002?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_003',
        'category': 'theory',
        'audit_question': 'Can a strict assessor invalidate the theory claim represented by AS_003?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_004',
        'category': 'baseline',
        'audit_question': 'Can a strict assessor invalidate the baseline claim represented by AS_004?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_005',
        'category': 'adapter',
        'audit_question': 'Can a strict assessor invalidate the adapter claim represented by AS_005?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_006',
        'category': 'reproducibility',
        'audit_question': 'Can a strict assessor invalidate the reproducibility claim represented by AS_006?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_007',
        'category': 'hygiene',
        'audit_question': 'Can a strict assessor invalidate the hygiene claim represented by AS_007?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_008',
        'category': 'claim',
        'audit_question': 'Can a strict assessor invalidate the claim claim represented by AS_008?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_009',
        'category': 'artifact',
        'audit_question': 'Can a strict assessor invalidate the artifact claim represented by AS_009?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_010',
        'category': 'benchmark',
        'audit_question': 'Can a strict assessor invalidate the benchmark claim represented by AS_010?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_011',
        'category': 'theory',
        'audit_question': 'Can a strict assessor invalidate the theory claim represented by AS_011?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_012',
        'category': 'baseline',
        'audit_question': 'Can a strict assessor invalidate the baseline claim represented by AS_012?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_013',
        'category': 'adapter',
        'audit_question': 'Can a strict assessor invalidate the adapter claim represented by AS_013?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_014',
        'category': 'reproducibility',
        'audit_question': 'Can a strict assessor invalidate the reproducibility claim represented by AS_014?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_015',
        'category': 'hygiene',
        'audit_question': 'Can a strict assessor invalidate the hygiene claim represented by AS_015?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_016',
        'category': 'claim',
        'audit_question': 'Can a strict assessor invalidate the claim claim represented by AS_016?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_017',
        'category': 'artifact',
        'audit_question': 'Can a strict assessor invalidate the artifact claim represented by AS_017?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_018',
        'category': 'benchmark',
        'audit_question': 'Can a strict assessor invalidate the benchmark claim represented by AS_018?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_019',
        'category': 'theory',
        'audit_question': 'Can a strict assessor invalidate the theory claim represented by AS_019?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_020',
        'category': 'baseline',
        'audit_question': 'Can a strict assessor invalidate the baseline claim represented by AS_020?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_021',
        'category': 'adapter',
        'audit_question': 'Can a strict assessor invalidate the adapter claim represented by AS_021?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_022',
        'category': 'reproducibility',
        'audit_question': 'Can a strict assessor invalidate the reproducibility claim represented by AS_022?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_023',
        'category': 'hygiene',
        'audit_question': 'Can a strict assessor invalidate the hygiene claim represented by AS_023?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_024',
        'category': 'claim',
        'audit_question': 'Can a strict assessor invalidate the claim claim represented by AS_024?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_025',
        'category': 'artifact',
        'audit_question': 'Can a strict assessor invalidate the artifact claim represented by AS_025?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_026',
        'category': 'benchmark',
        'audit_question': 'Can a strict assessor invalidate the benchmark claim represented by AS_026?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_027',
        'category': 'theory',
        'audit_question': 'Can a strict assessor invalidate the theory claim represented by AS_027?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_028',
        'category': 'baseline',
        'audit_question': 'Can a strict assessor invalidate the baseline claim represented by AS_028?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_029',
        'category': 'adapter',
        'audit_question': 'Can a strict assessor invalidate the adapter claim represented by AS_029?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_030',
        'category': 'reproducibility',
        'audit_question': 'Can a strict assessor invalidate the reproducibility claim represented by AS_030?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_031',
        'category': 'hygiene',
        'audit_question': 'Can a strict assessor invalidate the hygiene claim represented by AS_031?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_032',
        'category': 'claim',
        'audit_question': 'Can a strict assessor invalidate the claim claim represented by AS_032?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_033',
        'category': 'artifact',
        'audit_question': 'Can a strict assessor invalidate the artifact claim represented by AS_033?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_034',
        'category': 'benchmark',
        'audit_question': 'Can a strict assessor invalidate the benchmark claim represented by AS_034?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_035',
        'category': 'theory',
        'audit_question': 'Can a strict assessor invalidate the theory claim represented by AS_035?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_036',
        'category': 'baseline',
        'audit_question': 'Can a strict assessor invalidate the baseline claim represented by AS_036?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_037',
        'category': 'adapter',
        'audit_question': 'Can a strict assessor invalidate the adapter claim represented by AS_037?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_038',
        'category': 'reproducibility',
        'audit_question': 'Can a strict assessor invalidate the reproducibility claim represented by AS_038?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_039',
        'category': 'hygiene',
        'audit_question': 'Can a strict assessor invalidate the hygiene claim represented by AS_039?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
    {
        'attack_id': 'AS_040',
        'category': 'claim',
        'audit_question': 'Can a strict assessor invalidate the claim claim represented by AS_040?',
        'expected_repository_answer': 'The answer must be backed by a verifier, a ledger, and a replayable evidence object.',
        'repair_policy': 'Do not answer with prose only; add or update an executable check and include it in verify_all.py.',
        'severity': 'P1',
    },
]
def categories() -> list[str]:
    return sorted({item['category'] for item in ATTACK_SURFACE})
def by_category(category: str) -> list[dict[str,str]]:
    return [item for item in ATTACK_SURFACE if item['category'] == category]
def attack_surface_summary() -> dict[str,int]:
    return {category: len(by_category(category)) for category in categories()}
