from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path

@dataclass(frozen=True)
class SyncEntry:
    path: str
    bytes: int
    category: str
    upload_mode: str
    rationale: str

TEXT_SUFFIXES={'.py','.md','.tex','.bib','.bst','.cls','.csv','.json','.txt','.cff','.yml','.yaml','.conf','.cedar','.sh'}
BINARY_SUFFIXES={'.pdf','.so','.zip','.gz'}
HEAVY_LIMIT=750_000

def classify(path: Path, root: Path) -> SyncEntry:
    rel=path.relative_to(root).as_posix()
    size=path.stat().st_size
    if any(part in {'__pycache__','.ipynb_checkpoints'} for part in path.parts):
        return SyncEntry(rel,size,'excluded_cache','exclude','cache/transient')
    if path.suffix in {'.aux','.log','.out','.bbl','.blg','.synctex'}:
        return SyncEntry(rel,size,'excluded_latex_transient','exclude','LaTeX transient')
    if path.suffix == '.so' and '/vendor_python/' in '/' + rel:
        return SyncEntry(rel,size,'vendored_binary','direct_binary','pinned offline dependency needed for reviewer replay')
    if size > HEAVY_LIMIT:
        return SyncEntry(rel,size,'large_evidence','manifest_only','large deterministic evidence is regenerated by artifact replay')
    if path.suffix in TEXT_SUFFIXES:
        return SyncEntry(rel,size,'text','direct','UTF-8 text file suitable for GitHub tree upload')
    if path.suffix in BINARY_SUFFIXES:
        return SyncEntry(rel,size,'binary','direct_binary','binary but below repository threshold')
    return SyncEntry(rel,size,'other','direct','small file')

def _is_generated_fixture(path: Path, root: Path) -> bool:
    try:
        rel = path.relative_to(root).as_posix()
    except ValueError:
        return False
    return '/artifact/subjects/fixtures/' in '/' + rel or rel.startswith('artifact/subjects/fixtures/')

def build_sync_manifest(root: Path) -> list[SyncEntry]:
    entries = []
    for p in root.rglob('*'):
        if not p.is_file():
            continue
        if _is_generated_fixture(p, root):
            continue
        entries.append(classify(p, root))
    return sorted(entries, key=lambda e:e.path)

def write_manifest(root: Path, output: Path) -> None:
    rows=build_sync_manifest(root)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open('w', encoding='utf-8', newline='') as f:
        w=csv.DictWriter(f, fieldnames=['path','bytes','category','upload_mode','rationale'])
        w.writeheader(); w.writerows([e.__dict__ for e in rows])
