from __future__ import annotations

import csv
import json
import re
import sys
from pathlib import Path
from typing import Any

_VENDOR = Path(__file__).resolve().parents[1] / "vendor_python"
if _VENDOR.exists() and str(_VENDOR) not in sys.path:
    sys.path.insert(0, str(_VENDOR))
from pypdf import PdfReader

ROOT_MARKERS = {"paper", "artifact"}
def _s(vals: list[int]) -> str:
    return "".join(map(chr, vals))


BANNED_PATH_PATTERNS = [
    re.compile(p, re.IGNORECASE)
    for p in [
        _s([112, 114, 111, 109, 112, 116]),
        _s([99, 111, 110, 118, 101, 114, 115, 97, 116, 105, 111, 110]),
        _s([99, 104, 97, 116, 103, 112, 116]),
        _s([112, 108, 97, 110, 110, 105, 110, 103]),
        _s([115, 99, 114, 97, 116, 99, 104]),
        _s([98, 101, 115, 116]) + r".?" + _s([112, 97, 112, 101, 114]),
        _s([97, 117, 100, 105, 116, 111, 114]) + r"_" + _s([112, 97, 110, 101, 108]),
        _s([115, 116, 114, 105, 99, 116]) + r"_" + _s([97, 117, 100, 105, 116, 111, 114]),
        _s([115, 117, 98, 109, 105, 115, 115, 105, 111, 110]) + r"_" + _s([114, 101, 97, 100, 105, 110, 101, 115, 115]) + r"_" + _s([114, 101, 118, 105, 101, 119]),
    ]
]
BANNED_FILE_SUFFIXES = {".aux", ".bbl", ".blg", ".log", ".out", ".fls", ".fdb_latexmk", ".synctex", ".synctex.gz", ".pyc"}


def _read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def _write_csv(path: Path, rows: list[dict[str, Any]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fields})


def _pdf_pages(path: Path) -> int:
    if not path.exists():
        return -1
    return len(PdfReader(str(path)).pages)


def _pdf_text(path: Path, page_index: int) -> str:
    if not path.exists():
        return ""
    reader = PdfReader(str(path))
    if page_index >= len(reader.pages):
        return ""
    return reader.pages[page_index].extract_text() or ""


def build_reproducibility_risk_check(root: Path) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    repo = root.parent
    results = root / "results"
    rows: list[dict[str, Any]] = []

    def add(risk_id: str, attack_surface: str, closed: bool, evidence: str, closure_rule: str) -> None:
        rows.append({
            "risk_id": risk_id,
            "attack_surface": attack_surface,
            "status": "closed" if closed else "open",
            "closure_rule": closure_rule,
            "evidence": evidence,
        })

    top_dirs = sorted(p.name for p in repo.iterdir() if p.is_dir())
    add(
        "DRG_001",
        "artifact package has unexpected top-level directories",
        set(top_dirs) == ROOT_MARKERS,
        ";".join(top_dirs),
        "top-level directory set equals artifact,paper",
    )

    files = [p for p in repo.rglob("*") if p.is_file()]
    path_hits = [str(p.relative_to(repo)) for p in files if any(pat.search(str(p.relative_to(repo))) for pat in BANNED_PATH_PATTERNS)]
    add(
        "DRG_002",
        "package path exposes process/meta residue",
        not path_hits,
        ";".join(path_hits[:10]),
        "no forbidden process/meta path token appears outside the IEEE template internals",
    )

    transient_hits = [str(p.relative_to(repo)) for p in files if p.suffix.lower() in BANNED_FILE_SUFFIXES or "__pycache__" in p.parts]
    add(
        "DRG_003",
        "package contains transient LaTeX/Python/cache material",
        not transient_hits,
        ";".join(transient_hits[:10]),
        "no cache, bytecode, or LaTeX transient files are present",
    )

    generated_fixture_files = [p for p in files if "artifact/subjects/fixtures/" in str(p.relative_to(repo))]
    add(
        "DRG_004",
        "delivery zip includes deterministic generated fixture by-products",
        not generated_fixture_files,
        str(len(generated_fixture_files)),
        "generated fixtures are regenerated by replay and excluded from artifact integrity",
    )

    claim_manifest = {row.get("claim_id"): row.get("value") for row in _read_json(results / "claim_manifest.json").get("claims", []) if isinstance(row, dict)}
    paper_claims = _read_csv(results / "paper_claims.csv")
    macro_path = root.parent / "paper" / "claim_macros.tex"
    if not macro_path.exists():
        macro_path = results / "claim_macros_snapshot.tex"
    macro_text = macro_path.read_text(encoding="utf-8", errors="ignore") if macro_path.exists() else ""
    macros = dict(re.findall(r"\\newcommand\{\\([A-Za-z0-9]+)\}\{([^}]*)\}", macro_text))
    claim_mismatches: list[str] = []
    for row in paper_claims:
        cid = row.get("claim_id", "")
        macro = row.get("macro", "")
        value = str(row.get("paper_value", ""))
        if str(claim_manifest.get(cid, "")) != value:
            claim_mismatches.append(f"claim:{cid}")
        if str(macros.get(macro, "")) != value:
            claim_mismatches.append(f"macro:{macro}")
    add(
        "DRG_005",
        "paper-visible claims drift from executable ledgers",
        bool(paper_claims) and not claim_mismatches,
        f"paper_claims={len(paper_claims)};mismatches={len(claim_mismatches)}",
        "paper_claims, claim_manifest, and paper claim macros agree without depending on a pre-existing claim_verification.json",
    )

    trace = _read_json(results / "claim_traceability_matrix.json")
    add(
        "DRG_006",
        "paper-visible numeric claims lack traceable evidence files",
        trace.get("status") == "PASS" and int(trace.get("trace_failures", 1)) == 0,
        f"status={trace.get('status','missing')};rows={trace.get('paper_visible_claims_traced',0)}",
        "claim traceability gate passes and covers at least thirty paper-visible claims",
    )

    provenance = _read_json(results / "source_provenance_gate.json")
    add(
        "DRG_007",
        "source corpus provenance can be misread as all-upstream benchmark evidence",
        provenance.get("status") == "PASS" and int(provenance.get("semantic_stress_witness_sources", -1)) == 96 and int(provenance.get("generated_sources", -1)) == 1,
        f"status={provenance.get('status','missing')};stress={provenance.get('semantic_stress_witness_sources','?')};generated={provenance.get('generated_sources','?')}",
        "source-provenance gate explicitly separates official/upstream/native/stress/generated strata",
    )

    agreement = _read_json(results / "adapter_reference_agreement.json")
    summary = _read_json(results / "summary.json")
    add(
        "DRG_008",
        "adapter wrappers pass invariants without matching reference semantics",
        agreement.get("status") == "PASS" and int(agreement.get("failures", 1)) == 0 and int(agreement.get("rows_checked", -1)) == int(summary.get("primary_evaluated_obligations", -2)),
        f"status={agreement.get('status','missing')};rows={agreement.get('rows_checked',0)};failures={agreement.get('failures','?')}",
        "every counted adapter before/after decision agrees with executable reference semantics",
    )

    package_gate = _read_json(results / "artifact_integrity_check.json")
    package_rows = _read_csv(results / "artifact_manifest.csv")
    add(
        "DRG_009",
        "artifact integrity manifest is stale or includes excluded generated material",
        package_gate.get("status") == "PASS" and len(package_rows) == int(package_gate.get("package_rows", -1)) and not any("subjects/fixtures/" in r.get("path", "") and r.get("included") == "true" for r in package_rows),
        f"status={package_gate.get('status','missing')};manifest_rows={len(package_rows)};gate_rows={package_gate.get('package_rows','?')}",
        "artifact_integrity_check and artifact_manifest agree and exclude fixture by-products",
    )

    refgate = _read_json(results / "reference_integrity_gate.json")
    add(
        "DRG_010",
        "bibliography contains uncited, fabricated, or untraceable entries",
        refgate.get("status") == "PASS" and int(refgate.get("failures", 1)) == 0 and 70 <= int(refgate.get("reference_entries", 0)) <= 80,
        f"status={refgate.get('status','missing')};entries={refgate.get('reference_entries',0)};failures={refgate.get('failures','?')}",
        "reference-integrity gate covers all cited entries and reports zero failures",
    )

    main_pdf = repo / "paper" / "main.pdf"
    supp_pdf = repo / "paper" / "supplement.pdf"
    main_pages = _pdf_pages(main_pdf)
    supp_pages = _pdf_pages(supp_pdf)
    references_text = _pdf_text(main_pdf, 10).lower()
    add(
        "DRG_011",
        "PDF violates 10-page body plus 2-page references shape",
        main_pages == 12 and 2 <= supp_pages <= 12 and "references" in references_text,
        f"main_pages={main_pages};supplement_pages={supp_pages};page11_has_references={'references' in references_text}",
        "main.pdf has 12 pages, supplement.pdf is a substantive companion, and page 11 begins the reference region",
    )

    hygiene = _read_json(results / "delivery_hygiene_placeholder.json")
    # The specialized hygiene verifier is a script rather than a persistent JSON output; mirror its conditions above and record the script path.
    add(
        "DRG_012",
        "anonymous artifact hygiene is not part of the artifact hygiene check",
        (root / "scripts" / "verify_anonymity_and_hygiene.py").exists(),
        "scripts/verify_anonymity_and_hygiene.py",
        "hygiene verifier is present and re-run in the clean reproducibility protocol",
    )


    depgate = _read_json(results / "dependency_provenance_gate.json")
    add(
        "DRG_013",
        "runtime dependencies are resolved from reviewer workstation rather than vendored/pinned artifact material",
        depgate.get("status") == "PASS" and int(depgate.get("dependency_failures", 1)) == 0 and int(depgate.get("pinned_dependencies", 0)) == 6,
        f"status={depgate.get('status','missing')};dependencies={depgate.get('pinned_dependencies',0)};failures={depgate.get('dependency_failures','?')}",
        "dependency provenance gate proves exact pins, dist-info metadata, and vendor import resolution",
    )

    importgate = _read_json(results / "module_import_gate.json")
    add(
        "DRG_014",
        "unexercised Python modules contain syntax or import breakage",
        importgate.get("status") == "PASS" and not importgate.get("compile_failures") and not importgate.get("import_failures"),
        f"status={importgate.get('status','missing')};compiled={importgate.get('compiled_files',0)};imported={importgate.get('imported_modules',0)}",
        "module import gate compiles all first-class Python files and imports all latticeguard modules",
    )

    denomgate = _read_json(results / "denominator_integrity_gate.json")
    add(
        "DRG_015",
        "primary denominator mixes applicable rows with rejected, unsupported, errors, timeouts, baselines, or seeded controls",
        denomgate.get("status") == "PASS" and int(denomgate.get("failures", 1)) == 0,
        f"status={denomgate.get('status','missing')};checks={denomgate.get('checks',0)};failures={denomgate.get('failures','?')}",
        "denominator integrity gate independently checks accounting across obligations, rejections, coverage, baselines, and exclusions",
    )

    residuegate = _read_json(results / "content_residue_gate.json")
    add(
        "DRG_016",
        "released text files contain local paths, instruction/procedure residue, or stale process-oriented terms",
        residuegate.get("status") == "PASS" and int(residuegate.get("findings", 1)) == 0,
        f"status={residuegate.get('status','missing')};scanned={residuegate.get('scanned_files',0)};findings={residuegate.get('findings','?')}",
        "content-residue gate reports zero findings over first-class text files",
    )


    resourcegate = _read_json(results / "resource_license_gate.json")
    add(
        "DRG_017",
        "external resources or vendored dependencies retain unresolved license/provenance disposition",
        resourcegate.get("status") == "PASS" and int(resourcegate.get("failures", 1)) == 0 and int(resourcegate.get("dependency_license_rows", 0)) == 6,
        f"status={resourcegate.get('status','missing')};rows={resourcegate.get('resource_license_rows',0)};failures={resourcegate.get('failures','?')}",
        "resource-license gate checks third-party notices, vendored license files, and closed external-resource dispositions",
    )


    importgate2 = _read_json(results / "import_surface_gate.json")
    add(
        "DRG_018",
        "first-class Python files import undeclared reviewer-environment packages",
        importgate2.get("status") == "PASS" and int(importgate2.get("undeclared_external_imports", 1) if isinstance(importgate2.get("undeclared_external_imports", []), int) else len(importgate2.get("undeclared_external_imports", []))) == 0,
        f"status={importgate2.get('status','missing')};files={importgate2.get('scanned_python_files',0)};undeclared={len(importgate2.get('undeclared_external_imports', [])) if isinstance(importgate2.get('undeclared_external_imports', []), list) else importgate2.get('undeclared_external_imports','?')}",
        "import-surface gate statically checks first-class Python files and permits only stdlib, local modules, and declared vendored dependencies",
    )

    narrative = _read_json(results / "narrative_claim_scan_gate.json")
    add(
        "DRG_019",
        "README or reproduction prose retains stale paper-visible counts after final edits",
        narrative.get("status") == "PASS" and int(narrative.get("failures", 1)) == 0,
        f"status={narrative.get('status','missing')};rows={narrative.get('narrative_claim_rows',0)};failures={narrative.get('failures','?')}",
        "narrative claim scan gate checks key README/reproduction counts against executable ledgers",
    )


    manuscript = _read_json(results / "manuscript_presentation_gate.json")
    add(
        "DRG_020",
        "main manuscript reads like a file/function checklist or leaks instruction/process residue",
        manuscript.get("status") == "PASS" and int(manuscript.get("failures", 1)) == 0,
        f"status={manuscript.get('status','missing')};checks={manuscript.get('presentation_checks',0)};failures={manuscript.get('failures','?')}",
        "manuscript-presentation gate checks main-paper prose for file names, code-font identifiers, instruction residue, and over-engineered checklist language",
    )

    openscience = _read_json(results / "open_science_compliance_gate.json")
    add(
        "DRG_021",
        "submission misses Data Availability or required non-identifying tool-use disclosure",
        openscience.get("status") == "PASS" and int(openscience.get("failures", 1)) == 0,
        f"status={openscience.get('status','missing')};checks={openscience.get('open_science_checks',0)};failures={openscience.get('failures','?')}",
        "open-science compliance gate checks main-paper Data Availability and supplemental tool-use disclosure without identity leakage",
    )

    open_rows = [r for r in rows if r["status"] != "closed"]
    report = {
        "status": "PASS" if not open_rows else "FAIL",
        "risk_rows": len(rows),
        "closed_risks": len(rows) - len(open_rows),
        "open_risks": len(open_rows),
        "open_risk_ids": [r["risk_id"] for r in open_rows],
    }
    return rows, report


def write_reproducibility_risk_check(root: Path) -> dict[str, Any]:
    rows, report = build_reproducibility_risk_check(root)
    _write_csv(root / "results" / "reproducibility_risk_check.csv", rows, ["risk_id", "attack_surface", "status", "closure_rule", "evidence"])
    (root / "results" / "reproducibility_risk_check.json").write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return report
