#!/usr/bin/env python3
"""Full-run evidence verifier for LatticeGuard.

Verifies the full-run ledgers generated by run_full_evaluation.py plus the
postprocessed seeded-counterexample replay ledgers. It does not treat OPA as
executed; OPA must remain a pre-result exclusion unless a real CLI is pinned and
rerun in a later protocol amendment.
"""
from __future__ import annotations
import sys

sys.dont_write_bytecode = True

import csv, json, hashlib, re, subprocess
from pathlib import Path
from collections import Counter

ROOT = Path(__file__).resolve().parents[1]
REPO = ROOT.parent
RESULTS = ROOT / 'results'
EVIDENCE = ROOT / 'evidence'
sys.path.insert(0, str(ROOT))
from latticeguard.runtime_hygiene import python_bytecode_env
from latticeguard.opa_pinning import inspect_opa_candidate
from latticeguard.mechanized_law_kernel import write_mechanized_law_kernel
from latticeguard.semantic_counterexample_replay import write_semantic_counterexample_replay
from latticeguard.oracle_efficacy import write_oracle_efficacy
from latticeguard.research_quality_gate import write_quality_gate
from latticeguard.adapter_reference_agreement import write_adapter_reference_agreement
from latticeguard.reference_integrity_gate import write_reference_integrity_gate
from latticeguard.source_provenance_gate import write_source_provenance_gate
from latticeguard.claim_traceability import write_claim_traceability
from latticeguard.dependency_provenance_gate import write_dependency_provenance_gate
from latticeguard.module_import_gate import write_module_import_gate
from latticeguard.denominator_integrity_gate import write_denominator_integrity_gate
from latticeguard.content_residue_gate import write_content_residue_gate
from latticeguard.venue_requirements import write_venue_requirements
from latticeguard.reproducibility_risk_check import write_reproducibility_risk_check

RELATIONS = ['DD','DO','PA','DA','IE','ID','HC','HR','SR','RO','AR','SM']

FULL_CLAIM_PREREQUISITES = [
    'verify_research_quality.py',
    'verify_repository_depth.py',
    'verify_artifact_depth.py',
    'verify_evidence_challenge_check.py',
    'verify_proof_certificate.py',
    'verify_content_residue_gate.py',
    'verify_denominator_integrity_gate.py',
    'verify_module_import_gate.py',
    'verify_dependency_provenance_gate.py',
]

def ensure_full_claim_prerequisites() -> None:
    env = python_bytecode_env()
    for script in FULL_CLAIM_PREREQUISITES:
        subprocess.run([sys.executable, '-B', str(ROOT / 'scripts' / script)], check=True, stdout=subprocess.DEVNULL, env=env)


def sha256_file(path: Path) -> str:
    h=hashlib.sha256()
    with path.open('rb') as f:
        for chunk in iter(lambda:f.read(1024*1024), b''):
            h.update(chunk)
    return h.hexdigest()


def read_csv(path: Path):
    with path.open(newline='', encoding='utf-8') as f:
        return list(csv.DictReader(f))


def require(cond, msg, errors):
    if not cond:
        errors.append(msg)


def refresh_sha_ledger() -> None:
    """Synchronize SHA-256 ledger after prerequisite verifiers rewrite deterministic ledgers."""
    scripts_dir = ROOT / 'scripts'
    if str(scripts_dir) not in sys.path:
        sys.path.insert(0, str(scripts_dir))
    import run_full_evaluation as rfe  # type: ignore
    rfe.write_hashes()


def main() -> int:
    errors=[]
    ensure_full_claim_prerequisites()
    write_mechanized_law_kernel(ROOT)
    write_semantic_counterexample_replay(ROOT)
    write_oracle_efficacy(ROOT)
    write_quality_gate(ROOT)
    write_adapter_reference_agreement(ROOT)
    write_reference_integrity_gate(ROOT)
    write_dependency_provenance_gate(ROOT)
    write_module_import_gate(ROOT)
    write_denominator_integrity_gate(ROOT)
    write_content_residue_gate(ROOT)
    refresh_sha_ledger()
    required=[
        ROOT/'source_manifest.csv', RESULTS/'obligations.csv', RESULTS/'rejections.csv',
        RESULTS/'baseline_results.csv', RESULTS/'mutant_obligations.csv', RESULTS/'coverage.csv',
        RESULTS/'counterexamples.json', RESULTS/'minimization.csv', RESULTS/'adapter_exclusions.csv',
        RESULTS/'subject_exclusions.csv', RESULTS/'ablation_results.csv', RESULTS/'scalability.csv',
        RESULTS/'scalability_results.csv', RESULTS/'robustness.csv', RESULTS/'error_analysis.csv',
        RESULTS/'environment.json', RESULTS/'summary.json', RESULTS/'claim_manifest.json',
        RESULTS/'relation_contracts.csv', RESULTS/'adapter_semantics_matrix.csv',
        RESULTS/'public_subjects_manifest.csv', RESULTS/'paper_claims.csv',
        RESULTS/'predicate_evaluations.csv', RESULTS/'soundness_checks.csv',
        RESULTS/'model_check_cases.csv', RESULTS/'model_check_summary.json',
        RESULTS/'native_selftest_results.csv', RESULTS/'proof_certificate.json',
        RESULTS/'theorem_ledger.csv', RESULTS/'theorem_obligations.csv',
        RESULTS/'research_questions.csv', RESULTS/'novelty_matrix.csv',
        RESULTS/'research_quality_matrix.csv', RESULTS/'mechanized_law_kernel.csv',
        RESULTS/'mechanized_law_kernel.json', RESULTS/'oracle_efficacy_summary.csv',
        RESULTS/'oracle_efficacy_summary.json', RESULTS/'research_quality_gate_matrix.csv',
        RESULTS/'research_quality_gate_matrix.json', RESULTS/'adapter_reference_agreement.csv',
        RESULTS/'adapter_reference_agreement.json', RESULTS/'reference_integrity_gate.csv',
        RESULTS/'reference_integrity_gate.json',
        RESULTS/'source_provenance_gate.csv', RESULTS/'source_provenance_gate.json',
        RESULTS/'claim_traceability_matrix.csv', RESULTS/'claim_traceability_matrix.json',
        RESULTS/'dependency_provenance_gate.csv', RESULTS/'dependency_provenance_gate.json',
        RESULTS/'module_import_gate.csv', RESULTS/'module_import_gate.json',
        RESULTS/'denominator_integrity_gate.csv', RESULTS/'denominator_integrity_gate.json',
        RESULTS/'content_residue_gate.csv', RESULTS/'content_residue_gate.json',
        EVIDENCE/'SHA256SUMS.csv'
    ]
    for p in required:
        require(p.exists(), f'missing required file: {p.relative_to(ROOT)}', errors)
    if errors:
        print(json.dumps({'status':'FAIL','errors':errors}, indent=2)); return 1

    obligations=read_csv(RESULTS/'obligations.csv')
    rejections=read_csv(RESULTS/'rejections.csv')
    baseline=read_csv(RESULTS/'baseline_results.csv')
    mutants=read_csv(RESULTS/'mutant_obligations.csv')
    coverage=read_csv(RESULTS/'coverage.csv')
    minimization=read_csv(RESULTS/'minimization.csv')
    exclusions=read_csv(RESULTS/'adapter_exclusions.csv')
    source_manifest=read_csv(ROOT/'source_manifest.csv')
    sha_rows=read_csv(EVIDENCE/'SHA256SUMS.csv')
    summary=json.loads((RESULTS/'summary.json').read_text())
    claim_manifest=json.loads((RESULTS/'claim_manifest.json').read_text())
    counterexamples=json.loads((RESULTS/'counterexamples.json').read_text())
    relation_contracts=read_csv(RESULTS/'relation_contracts.csv')
    adapter_semantics=read_csv(RESULTS/'adapter_semantics_matrix.csv')
    public_subjects=read_csv(RESULTS/'public_subjects_manifest.csv')
    paper_claims=read_csv(RESULTS/'paper_claims.csv')
    predicate_rows=read_csv(RESULTS/'predicate_evaluations.csv')
    soundness_rows=read_csv(RESULTS/'soundness_checks.csv')
    model_cases=read_csv(RESULTS/'model_check_cases.csv')
    model_summary=json.loads((RESULTS/'model_check_summary.json').read_text())
    native_selftests=read_csv(RESULTS/'native_selftest_results.csv')
    proof_certificate=json.loads((RESULTS/'proof_certificate.json').read_text())
    theorem_rows=read_csv(RESULTS/'theorem_ledger.csv')
    theorem_obligations=read_csv(RESULTS/'theorem_obligations.csv')
    research_questions=read_csv(RESULTS/'research_questions.csv')
    novelty_rows=read_csv(RESULTS/'novelty_matrix.csv')
    research_quality=read_csv(RESULTS/'research_quality_matrix.csv')
    mechanized_rows=read_csv(RESULTS/'mechanized_law_kernel.csv')
    mechanized_summary=json.loads((RESULTS/'mechanized_law_kernel.json').read_text())
    oracle_efficacy=json.loads((RESULTS/'oracle_efficacy_summary.json').read_text())
    quality_gate=json.loads((RESULTS/'research_quality_gate_matrix.json').read_text())
    adapter_agreement=json.loads((RESULTS/'adapter_reference_agreement.json').read_text())
    reference_gate=json.loads((RESULTS/'reference_integrity_gate.json').read_text())

    ob_cols=set(obligations[0])
    required_ob_cols={'row_id','adapter_id','adapter_version','source_id','source_sha256','relation_id','law_id','candidate_id','applicability_predicate_id','applicability_status','rejection_reason','predicate_reason','predicate_witness_hash','predicate_inputs_hash','expected_invariant','before_decision','after_decision','oracle_status','diagnostic_hash','runtime_ms','memory_kb','replay_id'}
    require(required_ob_cols <= ob_cols, f'obligations.csv missing columns {sorted(required_ob_cols-ob_cols)}', errors)

    applicable=[r for r in obligations if r['applicability_status']=='APPLICABLE_EVALUATED']
    rejected=[r for r in obligations if r['applicability_status']=='REJECTED_NOT_COUNTED']
    unsupported=[r for r in obligations if r['applicability_status']=='UNSUPPORTED_NOT_COUNTED']
    adapters=sorted({r['adapter_id'] for r in applicable})
    opa_ready = inspect_opa_candidate(ROOT).get('status') == 'READY'
    require({'casbin_py','cedar_py'} <= set(adapters), f'core counted adapters missing from executed primary adapters {adapters}', errors)
    if opa_ready:
        require(set(adapters)=={'casbin_py','cedar_py','opa_rego_cli'}, f'hash-vetted OPA executable is present; expected exactly the three counted adapters, got {adapters}', errors)
    else:
        require(set(adapters)=={'casbin_py','cedar_py'}, f'unexpected executed primary adapters without hash-vetted OPA {adapters}', errors)
        require('opa_rego_cli' not in adapters, 'OPA appears executed despite exclusion', errors)
    for a in adapters:
        rels={r['relation_id'] for r in applicable if r['adapter_id']==a}
        require(set(RELATIONS)<=rels, f'{a} missing applicable relation coverage {sorted(set(RELATIONS)-rels)}', errors)
        srcs={r['source_id'] for r in applicable if r['adapter_id']==a}
        require(len(srcs)>=3, f'{a} has insufficient source coverage {sorted(srcs)}', errors)
    require(all(r['oracle_status']=='PASS' for r in applicable), 'applicable primary row not PASS', errors)
    require(len(applicable)==int(summary['primary_evaluated_obligations']), 'summary primary_evaluated_obligations mismatch', errors)
    require(sum(1 for r in applicable if r['oracle_status']=='PASS')==int(summary['primary_passes']), 'summary primary_passes mismatch', errors)
    require(sum(1 for r in applicable if r['oracle_status']=='FAIL')==int(summary['primary_real_failures']), 'summary primary_real_failures mismatch', errors)
    require(len(rejected)==int(summary['rejected_invalid_transformations']), 'summary rejected count mismatch obligations', errors)
    require(len(unsupported)==int(summary['unsupported_transformations']), 'summary unsupported count mismatch obligations', errors)
    require(all(r['oracle_status']=='UNSUPPORTED_NOT_COUNTED' for r in unsupported), 'unsupported rows counted as pass/fail', errors)


    # Executable predicate ledger: every candidate status must be produced by predicate_evaluations.csv, not only by a candidate constructor.
    require(predicate_rows, 'predicate_evaluations.csv is empty', errors)
    pred_by_candidate={r['candidate_id']:r for r in predicate_rows}
    obligation_candidate_status={}
    for r in obligations:
        obligation_candidate_status.setdefault(r['candidate_id'], r['applicability_status'])
        require(r['candidate_id'] in pred_by_candidate, f'obligation candidate lacks predicate evaluation: {r["candidate_id"]}', errors)
        if r['candidate_id'] in pred_by_candidate:
            pr=pred_by_candidate[r['candidate_id']]
            require(pr['computed_status']==r['applicability_status'], f'predicate status mismatch for {r["candidate_id"]}: {pr["computed_status"]} vs {r["applicability_status"]}', errors)
            require(pr.get('witness_hash','')==r.get('predicate_witness_hash',''), f'predicate witness hash mismatch for {r["candidate_id"]}', errors)
    require(all(r.get('computed_status') in {'APPLICABLE_EVALUATED','REJECTED_NOT_COUNTED','UNSUPPORTED_NOT_COUNTED'} for r in predicate_rows), 'predicate_evaluations.csv has invalid status', errors)
    require(len(predicate_rows)==len({r['candidate_id'] for r in obligations}), 'predicate_evaluations count must equal unique obligation candidates', errors)

    sound_by_candidate={r['candidate_id']:r for r in soundness_rows}
    require(len(sound_by_candidate)==len(pred_by_candidate), 'soundness_checks.csv must cover every predicate candidate', errors)
    for cid, pr in pred_by_candidate.items():
        sr=sound_by_candidate.get(cid)
        require(sr is not None, f'soundness row missing for {cid}', errors)
        if sr is not None:
            require(sr.get('applicability_status')==pr.get('computed_status'), f'soundness/predicate status mismatch for {cid}', errors)
            require(sr.get('soundness_check')=='PASS', f'law soundness check failed for {cid}', errors)

    # Bounded core semantic model check: theory-facing audit over a finite
    # deny-overrides RBAC algebra.
    require(model_summary.get('status')=='PASS', f'bounded model check status not PASS: {model_summary}', errors)
    require(int(model_summary.get('failures', -1))==0, 'bounded model checker reports failures', errors)
    require(int(model_summary.get('relations_covered', 0))==len(RELATIONS), 'bounded model checker does not cover all relations', errors)
    require(len(model_cases)==int(model_summary.get('cases_checked', -1)), 'model_check_cases.csv row count does not match model_check_summary', errors)
    require({r['relation_id'] for r in model_cases}==set(RELATIONS), 'model_check_cases.csv does not cover every relation', errors)
    require(all(r['model_check_status']=='PASS' for r in model_cases), 'bounded model-check case failed', errors)
    require(int(summary.get('bounded_model_checked_cases', -1))==len(model_cases), 'summary bounded_model_checked_cases mismatch', errors)
    require(int(summary.get('bounded_model_check_failures', -1))==0, 'summary bounded_model_check_failures mismatch', errors)
    require(proof_certificate.get('status')=='PASS', 'proof_certificate.json does not PASS', errors)
    require(int(proof_certificate.get('theorem_rows', 0))==12, 'proof certificate theorem row count mismatch', errors)
    require(int(proof_certificate.get('proof_obligations', 0))==48, 'proof certificate proof obligation count mismatch', errors)
    require(len(theorem_rows)==12 and {r['relation_id'] for r in theorem_rows}==set(RELATIONS), 'theorem_ledger.csv does not cover all relation theorems', errors)
    require(all(r.get('status')=='PASS' for r in theorem_rows), 'theorem ledger has non-PASS rows', errors)
    require(len(theorem_obligations)==48, 'theorem_obligations.csv must contain 48 rows', errors)
    require(all(r.get('status')=='PASS' for r in theorem_obligations), 'theorem proof obligation failed', errors)
    require(len(research_questions)==5, 'research_questions.csv must contain 5 RQs', errors)
    require(len(novelty_rows)==5, 'novelty_matrix.csv must contain 5 contribution rows', errors)
    require(len(research_quality)>=6 and all(str(r.get('status','')).startswith('closed') for r in research_quality), 'research_quality_matrix.csv must close all current quality rows', errors)
    require(mechanized_summary.get('status')=='PASS', 'mechanized_law_kernel.json does not PASS', errors)
    require(int(mechanized_summary.get('relations_covered',0))==len(RELATIONS), 'mechanized law kernel relation coverage mismatch', errors)
    require(int(mechanized_summary.get('failures',1))==0, 'mechanized law kernel reports failures', errors)
    require(len(mechanized_rows)==int(mechanized_summary.get('cases_checked',-1)) and len(mechanized_rows)>=400, 'mechanized law kernel row count mismatch or too small', errors)
    require(oracle_efficacy.get('status')=='PASS', 'oracle_efficacy_summary.json does not PASS', errors)
    require(int(oracle_efficacy.get('semantic_counterexamples_replayed',0))==int(summary.get('minimized_counterexamples',0)), 'oracle efficacy semantic replay mismatch', errors)
    require(quality_gate.get('status')=='PASS' and int(quality_gate.get('open_gaps',1))==0, 'research-quality gate matrix has open gaps', errors)
    require(adapter_agreement.get('status')=='PASS', 'adapter_reference_agreement.json does not PASS', errors)
    require(int(adapter_agreement.get('rows_checked',0))==len(applicable), 'adapter-reference agreement row count mismatch', errors)
    require(int(adapter_agreement.get('failures',1))==0, 'adapter-reference agreement reports failures', errors)
    require(reference_gate.get('status')=='PASS', 'reference_integrity_gate.json does not PASS', errors)
    require(70 <= int(reference_gate.get('reference_entries',0)) <= 80, 'reference-integrity gate reference count outside target range', errors)
    require(int(reference_gate.get('failures',1))==0, 'reference-integrity gate reports failures', errors)

    # Native public fixture self-tests: raw adapter-native files are executed
    # before normalization so provenance is not merely a label.
    require(len(native_selftests)>=400, f'too few native selftest rows for deep-benchmark configuration: {len(native_selftests)}', errors)
    require(all(r['status']=='PASS' for r in native_selftests), 'native public fixture selftest did not pass', errors)
    require({'casbin','cedar'} <= {r['adapter_family'] for r in native_selftests}, 'native selftests lack Casbin or Cedar rows', errors)
    require(int(summary.get('native_selftest_rows', -1))==len(native_selftests), 'summary native_selftest_rows mismatch', errors)
    require(int(summary.get('native_selftest_failures', -1))==0, 'summary native_selftest_failures mismatch', errors)

    # Rejection ledger mirrors rejected rows and is not part of applicable denominator.
    require(len(rejections)==len(rejected), 'rejections.csv count does not mirror rejected obligation rows', errors)
    rej_ids={r['candidate_id'] for r in rejections}
    applicable_ids={r['candidate_id'] for r in applicable}
    require(rej_ids.isdisjoint(applicable_ids), 'rejected candidate appears in applicable denominator', errors)
    require(all(r['would_be_unsound_if_counted']=='yes' for r in rejections), 'rejection row missing unsoundness flag', errors)

    # Mutant/negative-control accounting.
    seeded=[r for r in baseline if r['baseline_id']=='SEEDED_MUTANT_POSITIVE_CONTROL']
    killed=[r for r in seeded if r['killed']=='true']
    require(len(seeded)==int(summary['seeded_mutant_rows']), 'seeded mutant row count mismatch', errors)
    require(len(killed)==int(summary['seeded_mutants_killed']), 'seeded mutant killed count mismatch', errors)
    require(len(mutants)==len(seeded), 'mutant_obligations.csv should expose all seeded baseline rows', errors)
    killed_mutant_ids=sorted({r['adapter_id'] for r in killed})
    require(len(killed_mutant_ids)>=4, f'too few mutant families killed: {killed_mutant_ids}', errors)
    require(len(applicable)>=2500, f'applicable primary obligations below deep-benchmark target: {len(applicable)}', errors)
    require(len(counterexamples)>=1500, f'minimized counterexamples below deep-benchmark target: {len(counterexamples)}', errors)
    require(len(predicate_rows)>=2000, f'predicate witnesses below deep-benchmark target: {len(predicate_rows)}', errors)
    require(len(counterexamples)==len(killed), 'counterexample count does not match killed seeded mutants', errors)
    require(len(minimization)==len(killed), 'minimization rows do not match killed seeded mutants', errors)
    require(all(r['validity_preserved']=='true' for r in minimization), 'minimization validity not preserved for all rows', errors)
    for ce in counterexamples:
        require(ce.get('scope') in {'seeded_negative_control','seeded_mutant_positive_control'}, 'counterexample scope must be seeded negative-control/positive-control', errors)
        if 'replay_material' in ce:
            for mat in ce.get('replay_material', []):
                require(mat.get('exists') is True, f"counterexample replay material missing: {mat}", errors)
                p=ROOT/mat['path']
                require(p.exists(), f"counterexample path missing on disk: {mat['path']}", errors)
                if p.exists():
                    require(sha256_file(p)==mat['sha256'], f"counterexample hash mismatch: {mat['path']}", errors)
        else:
            require(ce.get('replay_verified') is True, f"counterexample not replay verified: {ce.get('failure_id')}", errors)
            require('minimal_before_policy' in ce and 'minimal_after_policy' in ce and 'request' in ce, f"counterexample lacks inline replay material: {ce.get('failure_id')}", errors)
            require(bool(ce.get('material_hash')), f"counterexample lacks material_hash: {ce.get('failure_id')}", errors)

    # Baselines and ablations.
    baseline_ids={r['baseline_id'] for r in baseline}
    for bid in ['UPSTREAM_ONLY','CROSS_ADAPTER_DIFFERENTIAL_ONLY','NO_APPLICABILITY_GATE','RANDOM_VALID_PERTURB','PROPERTY_GENERATOR_NO_REJECTION','CROSS_VERSION_DIFFERENTIAL_PRECHECK','LATTICEGUARD_FULL_ORACLE','SEEDED_MUTANT_POSITIVE_CONTROL']:
        require(bid in baseline_ids, f'missing baseline {bid}', errors)
    nogate=[r for r in baseline if r['baseline_id']=='NO_APPLICABILITY_GATE']
    require(nogate and 'invalid_candidates_would_be_counted=' in nogate[0]['oracle_status'], 'no applicability baseline lacks invalid count', errors)

    # OPA must be either counted through the hash-gated pinning contract or excluded before any result.
    opa=[r for r in exclusions if r['adapter_id']=='opa_rego_cli']
    if opa_ready:
        require(len(opa)==0, 'OPA exclusion row exists despite hash-vetted counted OPA execution', errors)
    else:
        require(len(opa)==1, 'OPA exclusion row missing/duplicated', errors)
        if opa:
            require(opa[0]['results_observed_before_exclusion']=='false', 'OPA exclusion was not pre-result', errors)
            require('missing_executable' in opa[0]['reason_code'], 'OPA exclusion reason is not missing executable', errors)

    # Source manifest hashes for local files.
    for row in source_manifest:
        lp=row.get('local_path','')
        if lp.startswith('subjects/'):
            p=ROOT/lp
            require(p.exists(), f'source manifest file missing: {lp}', errors)
            if p.exists():
                require(sha256_file(p)==row['sha256'], f'source manifest sha mismatch: {lp}', errors)

    # SHA ledger exact verification.
    for row in sha_rows:
        p=ROOT/row['path']
        require(p.exists(), f'SHA ledger path missing: {row["path"]}', errors)
        if p.exists():
            require(sha256_file(p)==row['sha256'], f'SHA mismatch for {row["path"]}', errors)

    # Claim manifest should not inflate primary failures/counterexamples.
    claims={c['claim_id']:c['value'] for c in claim_manifest.get('claims', []) if 'claim_id' in c}
    if claims:
        require(int(claims.get('executed_real_adapters', -1))==len(adapters), 'claim_manifest executed adapter count mismatch', errors)
        require(int(claims.get('primary_real_failures', -1))==0, 'claim_manifest primary real failures mismatch', errors)
        require(int(claims.get('minimized_counterexamples', -1))==len(counterexamples), 'claim_manifest minimized counterexamples mismatch', errors)
        require(int(claims.get('predicate_witnesses', -1))==len(predicate_rows), 'claim_manifest predicate_witnesses mismatch', errors)
        require(int(claims.get('adapter_reference_agreement_rows', -1))==int(adapter_agreement.get('rows_checked', -2)), 'claim_manifest adapter_reference_agreement_rows mismatch', errors)
        require(int(claims.get('adapter_reference_agreement_failures', -1))==0, 'claim_manifest adapter_reference_agreement_failures mismatch', errors)
        require(int(claims.get('reference_integrity_entries', -1))==int(reference_gate.get('reference_entries', -2)), 'claim_manifest reference_integrity_entries mismatch', errors)

    # anonymous evaluation checks: paper-visible quantitative claims must be manifest-backed.
    require(paper_claims, 'paper_claims.csv is empty', errors)
    for row in paper_claims:
        cid=row.get('claim_id','')
        require(cid in claims, f'paper claim {row.get("paper_label")} references unknown claim_id {cid}', errors)
        if cid in claims:
            require(str(row.get('paper_value','')) == str(claims[cid]), f'paper claim {row.get("paper_label")} value {row.get("paper_value")} != claim_manifest {claims[cid]}', errors)
    macro_path = REPO / 'paper' / 'claim_macros.tex'
    if not macro_path.exists():
        macro_path = RESULTS / 'claim_macros_snapshot.tex'
    require(macro_path.exists(), 'claim macro file missing from paper/ or artifact/results snapshot', errors)
    macros = {}
    if macro_path.exists():
        text = macro_path.read_text(encoding='utf-8')
        for m in re.finditer(r'\\newcommand\{\\([A-Za-z0-9]+)\}\{([^}]*)\}', text):
            macros[m.group(1)] = m.group(2)
        for row in paper_claims:
            name=row.get('macro','')
            require(name in macros, f'claim macro {name} missing from {macro_path.relative_to(REPO) if macro_path.exists() else macro_path}', errors)
            if name in macros:
                require(str(macros[name]) == str(row.get('paper_value','')), f'claim macro {name}={macros[name]} does not match paper_claims value {row.get("paper_value")}', errors)

    # anonymous evaluation checks: public subject stratum, relation contracts, adapter semantics, ablations, scalability.
    require(len(public_subjects) >= 100, f'expected >=100 public/native subject rows in the deep benchmark configuration, got {len(public_subjects)}', errors)
    require(any('casbin' in r.get('source_id','') or 'casbin' in r.get('source_url','') for r in public_subjects), 'public subject manifest lacks Casbin slice', errors)
    require(any('cedar' in r.get('source_id','') or 'cedar' in r.get('source_url','') for r in public_subjects), 'public subject manifest lacks Cedar slice', errors)
    native_rows=[r for r in source_manifest if r.get('kind')=='native_public_fixture']
    require(len(native_rows)>=200, f'expected deep native public fixture files in the deep benchmark configuration, got {len(native_rows)}', errors)
    require(any(r.get('adapter_id')=='casbin' for r in native_rows), 'native fixture manifest lacks Casbin files', errors)
    require(any(r.get('adapter_id')=='cedar' for r in native_rows), 'native fixture manifest lacks Cedar files', errors)
    require({r['relation_id'] for r in relation_contracts} == set(RELATIONS), 'relation_contracts.csv does not cover all frozen relations', errors)
    require({'casbin_py','cedar_py','opa_rego_cli'} <= {r['adapter_id'] for r in adapter_semantics}, 'adapter_semantics_matrix.csv missing adapter/exclusion rows', errors)
    ablations = read_csv(RESULTS/'ablation_results.csv')
    ablation_ids = {r['ablation_id'] for r in ablations}
    required_ablation_ids = {'remove_applicability_predicates','remove_invalid_transformation_rejection','remove_counterexample_minimization','public_subjects_only','generated_law_probes_only','without_cross_adapter_recheck','without_hierarchy_refactoring_relations'} | {f'single_relation_{rel}' for rel in RELATIONS}
    require(required_ablation_ids <= ablation_ids, f'ablation_results.csv missing ids {sorted(required_ablation_ids-ablation_ids)}', errors)
    scalability = read_csv(RESULTS/'scalability.csv')
    scalability_axes = {r['axis'] for r in scalability}
    required_axes = {'rule_count','principal_resource_action_count','hierarchy_depth','hierarchy_branching_factor','request_count','relation_families_enabled','adapters_enabled'}
    require(required_axes <= scalability_axes, f'scalability.csv missing axes {sorted(required_axes-scalability_axes)}', errors)
    for row in source_manifest:
        lp=row.get('local_path','')
        require(not Path(lp).is_absolute(), f'source_manifest local_path is not artifact-relative: {lp}', errors)

    verification={
        'status':'FAIL' if errors else 'PASS',
        'errors':errors,
        'executed_primary_adapters':adapters,
        'excluded_primary_adapters':[r['adapter_id'] for r in exclusions],
        'applicable_primary_obligations':len(applicable),
        'primary_passes':sum(1 for r in applicable if r['oracle_status']=='PASS'),
        'primary_failures':sum(1 for r in applicable if r['oracle_status']=='FAIL'),
        'rejected_invalid_transformations':len(rejections),
        'unsupported_not_counted':len(unsupported),
        'seeded_mutant_rows':len(seeded),
        'seeded_mutants_killed':len(killed),
        'seeded_counterexamples':len(counterexamples),
        'relation_ids':RELATIONS,
        'theorem_rows':len(theorem_rows),
        'proof_obligations':len(theorem_obligations),
        'research_questions':len(research_questions),
        'adapter_reference_agreement_rows': int(adapter_agreement.get('rows_checked', 0)),
        'reference_integrity_entries': int(reference_gate.get('reference_entries', 0)),
    }
    (RESULTS/'claim_verification.json').write_text(json.dumps(verification, indent=2, sort_keys=True)+'\n')
    print(json.dumps(verification, indent=2, sort_keys=True))
    return 1 if errors else 0

if __name__ == '__main__':
    raise SystemExit(main())
